use Inf21

INSERT INTO Preguntas(IdPreguntas, Preguntas)
values (1, 'Resistencia es conocida como:')
INSERT INTO Preguntas values (2, '¿Cuántas esculturas hay en Resistencia?')
INSERT INTO Preguntas values (3,'¿En qué sectores se divide geográficamente la provincia del Chaco?')
INSERT INTO Preguntas values (4, 'Campo del Cielo: Patrimonio Cultural y Turístico del Chaco, ¿Dónde se ubica?')
INSERT INTO Preguntas values (5, 'Al norte el límite natural establecido entre la Provincia de Chaco y Formosa es:')
INSERT INTO Preguntas values (6, 'Al sur, el límite establecido entre la Provincia del Chaco y Santa Fe es:')
INSERT INTO Preguntas values (7, 'El ex ferrocarril General Belgrano conectaba a:')
INSERT INTO Preguntas values (8, 'En el ámbito automovilístico deportivo Chaco tiene un exponente a nivel nacional e internacional, ¿Quién es?')
INSERT INTO Preguntas values (9, 'En el ámbito de los juegos olímpicos, el Chaco tiene un medallista en:')
INSERT INTO Preguntas values (10, 'Marcela Gómez, chaqueña, participó en los Juegos Olímpicos de Tokio en:')
INSERT INTO Preguntas values (11, 'El club de fútbol más antiguo del Chaco es')
INSERT INTO Preguntas values (12, 'Por Decreto N° 1491 el Gobierno de la Provincia del Chaco se declaró a un instrumento musical como “Patrimonio Cultural de la provincia del Chaco”, ¿Cuál es?')
INSERT INTO Preguntas values (13, 'La palabra Chacú del cual deriva el nombre de nuestra provincia, tenía un significado ¿Cuál era?')
INSERT INTO Preguntas values (14, 'La superficie total de la provincia del Chaco es de:')
INSERT INTO Preguntas values (15, 'La población actual del Chaco oscila entre:')
INSERT INTO Preguntas values (16, '¿Quién fue el primer gobernador del Territorio Nacional del Chaco?')
INSERT INTO Preguntas values (17, 'Un escritor reconocido en el ámbito chaqueño recibió el Premio Pionero de la Letras Chaqueñas, otorgado por la provincia del Chaco y la SADE local en 1985. ¿Quién fue?')
INSERT INTO Preguntas values (18, 'En la bandera del Chaco hay un arado rodeado de 25 estrellas ¿Qué representan?')
INSERT INTO Preguntas values (19, 'En un emblemático edificio de la ciudad de Resistencia se encuentra un mural del reconocido pintor Emilio Pettoruti ¿Dónde se encuentra emplazado?')
INSERT INTO Preguntas values (20, 'La producción destacada chaqueña que perdura en la memoria y porla cual se la reconoce a la provincia fue:')
INSERT INTO Preguntas values (21, '¿Cuál es la flor provincial del Chaco?')
INSERT INTO Preguntas values (22, 'Un conjunto coral chaqueño fue reconocido como “Patrimonio Cultural Viviente” ¿Cuál es?')
INSERT INTO Preguntas values (23, 'En 1939 es erigida la Diócesis de Resistencia ¿Quién fue el primer obispo?')
INSERT INTO Preguntas values (24, 'El Puente General Belgrano que une las provincias de Chaco y Corrientes se terminó de construir en:')
INSERT INTO Preguntas values (25, '¿Quién fue el primer gobernador de la Provincia del Chaco?')
INSERT INTO Preguntas values (26, 'Desde cuándo existe la Provincia del Chaco:')
INSERT INTO Preguntas values (27, 'Nuestras primeras poblaciones originarias, pertenecían a las etnias:')
INSERT INTO Preguntas values (28, 'La primera ciudad colonial del Chaco fue')
INSERT INTO Preguntas values (29, 'San Fernando del Río Negro fue una')
INSERT INTO Preguntas values (30, '¿Qué reducciones franciscanas se fundaron en el actual territorio del Chaco a finales del siglo XVIII?')
INSERT INTO Preguntas values (31, 'La Gobernación del Chaco se creó en')
INSERT INTO Preguntas values (32, 'La ley 1532 divido a la Gobernación del Chaco en')
INSERT INTO Preguntas values (33, 'Las autoridades que administraban la Gobernación del Chaco')
INSERT INTO Preguntas values (34, 'La Conquista Militar del Chaco se produjo')
INSERT INTO Preguntas values (35, 'La llegada de los inmigrantes se dio a raíz')
INSERT INTO Preguntas values (36, 'A inicios del siglo XX, la actividad económica más importante del territorio era')
INSERT INTO Preguntas values (37, 'El tanino se desarrolló en')
INSERT INTO Preguntas values (38, 'Las localidades algodoneras fueron')
INSERT INTO Preguntas values (39, 'Nuestra primera constitución se promulgó en')
INSERT INTO Preguntas values (40, '¿Cuántos departamentos tiene la provincia del Chaco?')
INSERT INTO Preguntas values (41, '¿Cuántas rutas nacionales recorren la provincia?')
INSERT INTO Preguntas values (42, 'La Ruta Nacional 16 recorre entre:')
INSERT INTO Preguntas values (43, '¿Qué Parques Nacionales existen en el Chaco?')
INSERT INTO Preguntas values (44, 'Campo del Cielo es reconocido por')
INSERT INTO Preguntas values (45, 'Isla del Cerrito se realiza la:')
INSERT INTO Preguntas values (46, 'La Fiesta Provincial del Inmigrante se realiza en')
INSERT INTO Preguntas values (47, 'El Festival Nacional Taninero se desarrolla en')
INSERT INTO Preguntas values (48, 'La Fiesta Provincial del Chivo se desarrolla en')
INSERT INTO Preguntas values (49, 'La Fiesta Nacional del Algodón se desarrolla en')
INSERT INTO Preguntas values (50, 'Las Reservas Naturales del Chaco son')
INSERT INTO Preguntas values (51, 'La Feria de Artesanía Aborigen Chaqueña se realiza en')
INSERT INTO Preguntas values (52, '¿Qué curso de agua se encuentra emplazado entre la provincia del Chaco y Formosa?')
INSERT INTO Preguntas values (53, 'El relieve del Chaco característico es')
INSERT INTO Preguntas values (54, 'Entre los ríos autóctonos del Chaco, se encuentran:')
INSERT INTO Preguntas values (55, 'Juan José Castelli es considerada como')
INSERT INTO Preguntas values (56, 'La ciudad de las Breñas logró jugar en el Campeonato Argentino de Clubes en')
INSERT INTO Preguntas values (57, 'En el municipio de Colonia Benítez se encuentra')
INSERT INTO Preguntas values (58, 'La patrona de Barranqueras es')
INSERT INTO Preguntas values (59, 'El Patrono de la ciudad de Resistencia es:')
INSERT INTO Preguntas values (60, 'En Presidencia Roque Saénz Peña se encuentra:')
INSERT INTO Preguntas values (61, 'En Las Palmas se puede recorrer:')