use Inf21

INSERT INTO Respuestas(IdRespuestas, Respuesta, Estado)
values (1, 'a. La ciudad de las esculturas', '1')
INSERT INTO Respuestas values (2, 'c. 600', '1')
INSERT INTO Respuestas values (3, 'a. Litoral Chaqueño, centro Chaqueño e Impenetrable Chaqueño', '1')
INSERT INTO Respuestas values (4, 'c. 12 de Octubre', '1')
INSERT INTO Respuestas values (5, 'c. Bermejo', '1')
INSERT INTO Respuestas values (6, 'a. Paralelo 28', '1')
INSERT INTO Respuestas values (7, 'b. Puerto de Barranqueras con Salta', '1')
INSERT INTO Respuestas values (8, 'a. Juan Manuel Silva', '1')
INSERT INTO Respuestas values (9, 'a. Básquet', '1')
INSERT INTO Respuestas values (10, 'c. Atletismo', '1')
INSERT INTO Respuestas values (11, 'b. Sarmiento', '1')
INSERT INTO Respuestas values (12, 'b. N´viké', '1')
INSERT INTO Respuestas values (13, 'a. Caza comunal de animales', '1')
INSERT INTO Respuestas values (14, 'a. 99.633 Km²', '1')
INSERT INTO Respuestas values (15, 'c. 1.000.000', '1')
INSERT INTO Respuestas values (16, 'b. Gral. Julio de Vedia', '1')
INSERT INTO Respuestas values (17, 'b. Aledo Luis Meloni', '1')
INSERT INTO Respuestas values (18, 'a. Los departamentos provinciales', '1')
INSERT INTO Respuestas values (19, 'c. Casa de Gobierno', '1')
INSERT INTO Respuestas values (20, 'b. Algodón', '1')
INSERT INTO Respuestas values (21, 'c. Flor rosada del palo borracho', '1')
INSERT INTO Respuestas values (22, 'c. El coro Chelaalapí', '1')
INSERT INTO Respuestas values (23, 'b. Nicolás de Carlo', '1')
INSERT INTO Respuestas values (24, 'b. 1974', '1')
INSERT INTO Respuestas values (25, 'a. Felipe Gallardo', '1')
INSERT INTO Respuestas values (26, 'a. 8 de Agosto de 1951', '1')
INSERT INTO Respuestas values (27, 'e. Guaraníes', '0')
INSERT INTO Respuestas values (28, 'b. Concepción del Bermejo', '1')
INSERT INTO Respuestas values (29, 'b. Reducción de los jesuitas', '1')
INSERT INTO Respuestas values (30, 'c. Nuestra Señora de los Dolores de la Cangaye', '1')
INSERT INTO Respuestas values (31, 'b. 1862', '1')
INSERT INTO Respuestas values (32, 'a. Dos Gobernaciones (Chaco Austral y Chaco Central)', '1')
INSERT INTO Respuestas values (33, 'b. Eran nombradas por el Poder Ejecutivo Nacional', '1')
INSERT INTO Respuestas values (34, 'b. Al terminar la Guerra de la Triple Alianza', '1')
INSERT INTO Respuestas values (35, 'a. Ley Avellaneda sancionada en 1876', '1')
INSERT INTO Respuestas values (36, 'a. Algodón', '1')
INSERT INTO Respuestas values (37, 'c. Vicentini', '1')
INSERT INTO Respuestas values (38, 'c. Quitilipi, d. Machagai', '1')
INSERT INTO Respuestas values (39, 'a. 1951', '1')
INSERT INTO Respuestas values (40, 'a. 25', '1')
INSERT INTO Respuestas values (41, 'c. 3', '1')
INSERT INTO Respuestas values (42, 'b. Entre Resistencia y Pampa del Infierno', '1')
INSERT INTO Respuestas values (43, 'a. Parque Nacional Chaco', '1')
INSERT INTO Respuestas values (44, 'a. Museo a cielo abierto de meteoritos', '1')
INSERT INTO Respuestas values (45, 'a. Fiesta del Dorado', '1')
INSERT INTO Respuestas values (46, 'b. Las Breñas', '1')
INSERT INTO Respuestas values (47, 'c. Puerto Tirol', '1')
INSERT INTO Respuestas values (48, 'a. Pampa del Indio', '1')
INSERT INTO Respuestas values (49, 'c. Presidencia Roque Sáenz Peña', '1')
INSERT INTO Respuestas values (50, 'a. Reserva Natural Provincial Fuerte Esperanza, b. Parque Provincial Loro Hablador', '1')
INSERT INTO Respuestas values (51, 'c. Quitilipi', '1')
INSERT INTO Respuestas values (52, 'b. Río Bermejo', '1')
INSERT INTO Respuestas values (53, 'c. Llanura', '1')
INSERT INTO Respuestas values (54, 'b. Oro, c. Tragadero, e. Negro, f. Guaycurú', '1')
INSERT INTO Respuestas values (55, 'a. Portal del Impenetrable', '1')
INSERT INTO Respuestas values (56, 'a. Baloncesto', '1')
INSERT INTO Respuestas values (57, 'a. Museo Casa y Jardín Schulz', '1')
INSERT INTO Respuestas values (58, 'a. Inmaculada Concepción de la Virgen María', '1')
INSERT INTO Respuestas values (59, 'a. San Fernando Rey', '1')
INSERT INTO Respuestas values (60, 'c. Museo Casa y Jardín Schulz', '0')
INSERT INTO Respuestas values (61, 'a. Las ruinas del Ingenio Azucarero', '1')