# Generated by Django 3.2.6 on 2021-08-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntas', models.CharField(max_length=200, null=True)),
                ('respuesta1', models.CharField(max_length=200, null=True)),
                ('respuesta2', models.CharField(max_length=200, null=True)),
                ('respuesta3', models.CharField(max_length=200, null=True)),
                ('correcta', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'cuestionario',
            },
        ),
    ]
